### ISSUE TITLE
Add resources in the Resources page

### ISSUE THREAD

**Issue by souravcipher** [openprivacytech/openprivacytech.org#2]
Add educational resources(video, paper, tutorials) for Federated Learning, Differential Privacy, SMPC, FHE etc.

[here](https://github.com/OpenPrivacyTech/openprivacytech.org/blob/main/src/pages/resources.md).

**Comment by princefishthrower** [comment]
@souravcipher happy to take this one! Just assign me and I'll have a pull request by the end of the day saturday :)

**Comment by souravcipher** [comment]
Sure @princefishthrower, go for it. 

I'm closing this issue for now.

**Comment by princefishthrower** [comment]
@souravcipher - It's done in: https://github.com/openprivacytech/openprivacytech.org/pull/33. One question I have - would it be a good idea to add the Wikipedia article as the first of each section? Just for the reader to get a background on the topic before getting into the technical papers. I also changed the 3rd level heading to 2nd level since it's more semantically correct.
